# starting point https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/go?view=azure-devops
# this is NON-CONTENERIZED (NON-DOCKERIZE) build version. 
# https://aka.ms/yaml

# there is also Microsoft defined go step prepared already! https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/go?view=azure-devops

trigger:
  - master
  
pool:
  vmImage: 'ubuntu-latest'

variables:
    GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
    projectPath: $(GOPATH)/src/github.com/$(build.repository.name) # Path to the module's code

steps:
- task: GoTool@0
  inputs:
    version: '1.13.5'
- script: |
    go version
    echo 'MODULE PATH IS : $(projectPath)' 
    displayName: 'Show GO version used.'
- task: Go@0
  inputs:
    command: 'get'
    arguments: '-d'
    workingDirectory: '$(projectPath)'
- task: Go@0
  inputs:
    command: 'build'
    arguments: '-v'
    workingDirectory: '$(projectPath)'
    displayName: 'Building app.'

# flag withIntegrationTests is injected from Azure DevOps, and then used as regular boolean variable in the code.
- script: |
    echo 'MODULE PATH IS : $(projectPath)/airStations'
    echo 'RUNNING TESTS WITH `withIntegrationTests` flag set to : $(withIntegrationTests)'
    go test -v . -args -withIntegrationTests=$(withIntegrationTests)
  workingDirectory: '$(projectPath)/airStations'
  displayName: 'Run TESTS for AIRSTATIONS module'

- script: |
    echo 'MODULE PATH IS : $(projectPath)/api'
    echo 'RUNNING TESTS WITH `withIntegrationTests` flag set to : $(withIntegrationTests)'
    go test -v . -args -withIntegrationTests=$(withIntegrationTests)
  workingDirectory: '$(projectPath)/api'
  displayName: 'Run TESTS for API module'

- script: |
    echo 'MODULE PATH IS : $(projectPath)/geoLocalize'
    echo 'RUNNING TESTS WITH `withIntegrationTests` flag set to : $(withIntegrationTests)'
    go test -v . -args -withIntegrationTests=$(withIntegrationTests)  
  workingDirectory: '$(projectPath)/geoLocalize'
  displayName: 'Run TESTS for GEOLOCALIZE module'