# starting point https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/go?view=azure-devops
# this is NON-CONTENERIZED (NON-DOCKERIZE) build version. 
# https://aka.ms/yaml

trigger:
  - master
  
pool:
  vmImage: 'ubuntu-latest'
  
variables:
      GOBIN:  '$(GOPATH)/bin' # Go binaries path
      GOROOT: '/usr/local/go1.13' # Go installation path
      GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
      projectPath: $(GOPATH)/src/github.com/$(build.repository.name) # Path to the module's code
      #withIntegrationTests: true
    
steps:
- script: |
    mkdir -p '$(GOBIN)'
    mkdir -p '$(GOPATH)/pkg'
    mkdir -p '$(projectPath)'
    shopt -s extglob
    mv !(gopath) '$(projectPath)'
    echo '##vso[task.prependpath]$(GOBIN)'
    echo '##vso[task.prependpath]$(GOROOT)/bin'
    echo 'MODULE PATH IS : $(projectPath)' 
  displayName: 'Set up the Go workspace'
  
- script: |
    go version
  displayName: 'Show GO version used.'

- script: |
    go get -v -t -d ./...
    if [ -f Gopkg.toml ]; then
        curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
        dep ensure
    fi
  workingDirectory: '$(projectPath)'
  displayName: 'Get dependencies.'

- script: |
    go build -v .
  workingDirectory: '$(projectPath)'
  displayName: 'Building app.'

- script: |
    echo 'MODULE PATH IS : $(projectPath)/airStations'
    echo 'RUNNING TESTS WITH `withIntegrationTests` flag set to : $(withIntegrationTests)'
    go test -v . -args -withIntegrationTests=$(withIntegrationTests)
  workingDirectory: '$(projectPath)/airStations'
  displayName: 'Run TESTS for AIRSTATIONS module'

- script: |
    echo 'MODULE PATH IS : $(projectPath)/api'
    echo 'RUNNING TESTS WITH `withIntegrationTests` flag set to : $(withIntegrationTests)'
    go test -v . -args -withIntegrationTests=$(withIntegrationTests)
  workingDirectory: '$(projectPath)/api'
  displayName: 'Run TESTS for API module'

- script: |
    echo 'MODULE PATH IS : $(projectPath)/geoLocalize'
    echo 'RUNNING TESTS WITH `withIntegrationTests` flag set to : $(withIntegrationTests)'
    go test -v . -args -withIntegrationTests=$(withIntegrationTests)  
  workingDirectory: '$(projectPath)/geoLocalize'
  displayName: 'Run TESTS for GEOLOCALIZE module'