// Code generated by MockGen. DO NOT EDIT.
// Source: .\airStations\stationSensors.go

// Package airStations is a generated GoMock package.
package airStations

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockIStationsCapabiltiesFetcher is a mock of IStationsCapabiltiesFetcher interface
type MockIStationsCapabiltiesFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockIStationsCapabiltiesFetcherMockRecorder
}

// MockIStationsCapabiltiesFetcherMockRecorder is the mock recorder for MockIStationsCapabiltiesFetcher
type MockIStationsCapabiltiesFetcherMockRecorder struct {
	mock *MockIStationsCapabiltiesFetcher
}

// NewMockIStationsCapabiltiesFetcher creates a new mock instance
func NewMockIStationsCapabiltiesFetcher(ctrl *gomock.Controller) *MockIStationsCapabiltiesFetcher {
	mock := &MockIStationsCapabiltiesFetcher{ctrl: ctrl}
	mock.recorder = &MockIStationsCapabiltiesFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIStationsCapabiltiesFetcher) EXPECT() *MockIStationsCapabiltiesFetcherMockRecorder {
	return m.recorder
}

// DoAllMeasurmentsAPIcall mocks base method
func (m *MockIStationsCapabiltiesFetcher) DoAllMeasurmentsAPIcall() ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoAllMeasurmentsAPIcall")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DoAllMeasurmentsAPIcall indicates an expected call of DoAllMeasurmentsAPIcall
func (mr *MockIStationsCapabiltiesFetcherMockRecorder) DoAllMeasurmentsAPIcall() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoAllMeasurmentsAPIcall", reflect.TypeOf((*MockIStationsCapabiltiesFetcher)(nil).DoAllMeasurmentsAPIcall))
}
